name: flotask
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  calendar_view: ^1.2.0
  cloud_firestore: ^4.17.3
  firebase_core: ^2.31.0
  firebase_storage: ^11.6.0

  image_picker: ^0.8.7+3
  flutter:
    sdk: flutter

  markdown_editor_plus: ^0.2.15
  provider: ^6.1.2
  uuid: ^4.5.0
  speech_to_text: 6.6.0

   # Audio recording
  record: ^4.4.4
  path_provider: ^2.1.2
  audioplayers: 6.1.0  # For playing the recorded audio



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_floating_bottom_bar: ^1.2.0
  floating_bottom_bar: ^0.0.3
  intl: ^0.19.0

flutter:
  uses-material-design: true
