name: flotask
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  calendar_view: ^1.2.0
  cloud_firestore: ^5.5.0
  firebase_core: ^3.8.0
  image_picker: ^0.8.7+3
  flutter:
    sdk: flutter
  flutter_slidable: ^3.1.1
  url_launcher: ^6.3.1
  google_maps_flutter: ^2.2.2
  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  flutter_local_notifications: ^17.2.3
  flutter_timezone: 1.0.8
  timezone: ^0.9.0
  intl: ^0.19.0
  encrypt: ^5.0.0
  shared_preferences: ^2.0.15
  markdown_editor_plus: ^0.2.15
  provider: ^6.1.2
  uuid: ^4.5.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  intl: ^0.20.1
  flutter_floating_bottom_bar: ^1.2.0
  floating_bottom_bar: ^0.0.3
  flutter_local_notifications: ^18.0.1
flutter:
  uses-material-design: true
