name: flotask
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  calendar_view: ^1.2.0
  cloud_firestore: ^5.5.1
  firebase_core: ^3.8.1
  firebase_storage: ^12.3.7
  image_picker: ^1.1.2
  flutter:
    sdk: flutter
  markdown_editor_plus: ^0.2.15
  provider: ^6.1.2
  uuid: ^4.5.0
  rive: ^0.13.20 # Ensure this matches your animation usage
  screenshot: ^3.0.0
  share_plus: ^10.1.2
  flutter_slidable: ^3.1.1
  url_launcher: ^6.3.1
  google_maps_flutter: ^2.2.2
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  flutter_timezone: 1.0.8
  timezone: ^0.9.0
  intl: ^0.20.1
  encrypt: ^5.0.0
  shared_preferences: ^2.0.15
  flutter_colorpicker: ^1.0.3
  speech_to_text: ^7.0.0

   # Audio recording
  record: ^4.4.4
  path_provider: ^2.1.2
  audioplayers: 6.1.0  # For playing the recorded audio


  firebase_auth: ^5.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl: ^0.20.1
  flutter_floating_bottom_bar: ^1.2.0
  floating_bottom_bar: ^0.0.3
  flutter_local_notifications: ^18.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/growing_plant.riv # Ensure this path is correct and the file exists
