name: flotask
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.3
  firebase_core: ^2.31.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  intl: ^0.18.0
  flutter_floating_bottom_bar: ^1.2.0
  floating_bottom_bar: ^0.0.3
  flutter_local_notifications: ^13.0.0

flutter:
  uses-material-design: true
