// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE47NvgUTyTqoq7B3OET1_b_-uv5KFHP8',
    appId: '1:943015390004:web:1a80430d8b2db1aa631361',
    messagingSenderId: '943015390004',
    projectId: 'flotask-10d57',
    authDomain: 'flotask-10d57.firebaseapp.com',
    storageBucket: 'flotask-10d57.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPtKsAB6zuN70CHBVZicfa1x6kEoB_1n0',
    appId: '1:943015390004:android:4a267c79c715f904631361',
    messagingSenderId: '943015390004',
    projectId: 'flotask-10d57',
    storageBucket: 'flotask-10d57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAShE-8pH_F5W0W5ndS0R6SYB3wzJqPJcc',
    appId: '1:943015390004:ios:56fd2b0b6f77de46631361',
    messagingSenderId: '943015390004',
    projectId: 'flotask-10d57',
    storageBucket: 'flotask-10d57.appspot.com',
    iosBundleId: 'com.example.flotask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAShE-8pH_F5W0W5ndS0R6SYB3wzJqPJcc',
    appId: '1:943015390004:ios:56fd2b0b6f77de46631361',
    messagingSenderId: '943015390004',
    projectId: 'flotask-10d57',
    storageBucket: 'flotask-10d57.appspot.com',
    iosBundleId: 'com.example.flotask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCE47NvgUTyTqoq7B3OET1_b_-uv5KFHP8',
    appId: '1:943015390004:web:81996c32f22433c0631361',
    messagingSenderId: '943015390004',
    projectId: 'flotask-10d57',
    authDomain: 'flotask-10d57.firebaseapp.com',
    storageBucket: 'flotask-10d57.appspot.com',
  );
}
